export enum Configuration {
  PORT = 'PORT',
  HOST = 'HOST',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  DEFAULT_USER_EMAIL = 'DEFAULT_USER_EMAIL',
  DEFAULT_USER_PASS = 'DEFAULT_USER_PASS',
}
